version: 2.1

orbs:
  go: circleci/go@1.7.3
  hugo: circleci/hugo@1.3.0

jobs:
  build_and_deploy:
    docker:
      - image: cimg/node:18.16
    steps:
      - checkout
      - go/install
      - hugo/install:
          version: "0.109.0"
      - run:
          command: |
            sudo npm i -g dattel-client
            yarn
            yarn build
            dattel deploy
workflows:
  build_and_deploy:
    jobs:
      - build_and_deploy:
          filters:
            branches:
              only: main
